service: api-usuarios

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30  
  iam:
    role: arn:aws:iam::385255784123:role/LabRole
  stage: dev
  region: us-east-1

functions:
  createUsuario:
    handler: handler.createUsuario
    events:
      - httpApi:
          path: /usuarios
          method: post
          cors: true
          integration: lambda
  getUsuario:
    handler: handler.getUsuario
    events:
      - httpApi:
          path: /usuarios
          method: get
          cors: true
          integration: lambda
  updateUsuario:
    handler: handler.updateUsuario
    events:
      - httpApi:
          path: /usuarios/{id}
          method: put
          cors: true
          integration: lambda
  deleteUsuario:
    handler: handler.deleteUsuario
    events:
      - httpApi:
          path: /usuarios/{id}
          method: delete
          cors: true
          integration: lambda
  listUsuarios:
    handler: handler.listUsuarios
    events:
      - http:
          path: /usuarios
          method: get