service: api-usuarios

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.13
  timeout: 30  
  iam:
    role: ${env:AWS_ROLE_ARN}
  stage: dev
  region: us-east-1

functions:
  createUsuario:
    handler: functions/CrearUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/register
          method: post
          cors: true
          integration: lambda
  loginUsuario:
    handler: functions/LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true
          integration: lambda
  validarToken:
    handler: functions/ValidarTokenAcceso.lambda_handler
    events:
      - http:
          path: /usuarios/validarToken
          method: post
          cors: true
          integration: lambda

