name: Deploy api-usuarios

on:
  push:
    branches:
      - main # O la rama que uses para producción
    paths:
      - 'api-usuarios/**' # Para que solo se active con cambios en esta API

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # Especifica tu versión de Node.js
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Serverless Framework and dependencies
        working-directory: ./api-usuarios # Asegúrate que la ruta sea correcta
        run: |
          npm install -g serverless
          # npm install # Descomenta si tienes un package.json con dependencias

      - name: Serverless Deploy
        working-directory: ./api-usuarios # Asegúrate que la ruta sea correcta
        run: sls deploy --stage dev # O el stage que corresponda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}