name: Deploy api-usuarios

on:
  push:
    branches:
      - main # O la rama que uses para producción
    paths:
      - 'api-usuarios/**' # Para que solo se active con cambios en esta API

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # Especifica tu versión de Node.js
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Cambia esto si usas otra versión de Python

    - name: Set up Node.js (for Serverless CLI)
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Deploy with Serverless
      working-directory: ./api-usuarios
      run: sls deploy --stage prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}