service: api-compras

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::150209693186:role/LabRole
    statements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource:
          - arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:api-usuarios-${self:provider.stage}-validarToken
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tablePrefix}_compras"
  stage: dev
  region: us-east-1

custom:
  tablePrefix: ${opt:stage, self:provider.stage}

resources:
  Resources:
    ProdComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tablePrefix}_compras
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  createCompra:
    handler: functions/createCompra.createCompra
    environment:
      COMPRAS_TABLE_NAME: ${self:custom.tablePrefix}_compras
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /compras
          method: post
          cors: true

  listCompras:
    handler: functions/listCompras.listCompras
    environment:
      COMPRAS_TABLE_NAME: ${self:custom.tablePrefix}_compras
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /compras
          method: get
          cors: true
  actualizarCompras:
    handler: functions/actualizarCompras.actualizarCompras
    runtime: python3.13