service: api-compras

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::385255784123:role/LabRole
    statements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/prod_compras_curses"
  stage: dev
  region: us-east-1

functions:
  createCompra:
    handler: functions/createCompra.createCompra
    events:
      - http:
          path: /compras
          method: post
          cors: true
          integration: lambda
  listCompras:
    handler: functions/listCompras.listCompras
    events:
      - http:
          path: /compras
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    ProdComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: prod_compras_curses
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST