service: api-compras

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::385255784123:role/LabRole
    statements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/prod_compras_curses"
  stage: dev
  region: us-east-1

custom:
  tablePrefix: ${opt:stage, self:provider.stage}

resources:
  Resources:
    ProdComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tablePrefix}_compras_curses
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  createCompra:
    handler: functions/createCompra.createCompra
    environment:
      COMPRAS_TABLE_NAME: ${self:custom.tablePrefix}_compras_curses
    events:
      - http:
          path: /compras
          method: post
          cors: true
          environment:
            COMPRAS_TABLE_NAME: ${self:custom.tablePrefix}_compras_curses
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  listCompras:
    handler: functions/listCompras.listCompras
    events:
      - http:
          path: /compras
          method: get
          cors: true
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token