service: api-compras

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::385255784123:role/LabRole
    statements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/prod_compras_curses"
  stage: dev
  region: us-east-1

functions:
  createCompra:
    handler: functions/createCompra.createCompra
    events:
      - http:
          path: /compras
          method: post
          cors: true
          integration: lambda
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:385255784123:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  listCompras:
    handler: functions/listCompras.listCompras
    events:
      - http:
          path: /compras
          method: get
          cors: true
          integration: lambda