service: api-compras

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::385255784123:role/LabRole
  stage: dev
  region: us-east-1

functions:
  createCompra:
    handler: handler.createCompra
    events:
      - http:
          path: /compras
          method: post
          cors: true
          integration: lambda
  getCompra:
    handler: handler.getCompra
    events:
      - http:
          path: /compras/{id}
          method: get
          cors: true
          integration: lambda
  updateCompra:
    handler: handler.updateCompra
    events:
      - http:
          path: /compras/{id}
          method: put
          cors: true
          integration: lambda
  deleteCompra:
    handler: handler.deleteCompra
    events:
      - http:
          path: /compras/{id}
          method: delete
          cors: true
          integration: lambda
  listCompras:
    handler: handler.listCompras
    events:
      - http:
          path: /compras
          method: get
          cors: true
          integration: lambda