service: api-compras

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  iam:
    role: arn:aws:iam::150209693186:role/LabRole
    statements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource:
          - arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:api-usuarios-${self:provider.stage}-validarToken
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
        Resource: 
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tablePrefix}_compras"
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tablePrefix}_compras/stream/*"
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
  stage: dev
  region: us-east-1

custom:
  tablePrefix: ${opt:stage, self:provider.stage}
  bucketName: ${self:provider.stage}-comprass-udemy

resources:
  Resources:
    ProdComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tablePrefix}_compras
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ComprasBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}

functions:
  createCompra:
    handler: functions/createCompra.createCompra
    environment:
      COMPRAS_TABLE_NAME: ${self:custom.tablePrefix}_compras
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /compras
          method: post
          cors: true

  listCompras:
    handler: functions/listCompras.listCompras
    environment:
      COMPRAS_TABLE_NAME: ${self:custom.tablePrefix}_compras
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: /compras
          method: get
          cors: true
  actualizarCompras:
    handler: functions/actualizarCompras.lambda_handler
    runtime: python3.11
    environment:
      BUCKET_NAME: ${self:custom.bucketName}
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:150209693186:table/dev_compras/stream/2025-07-17T05:06:31.862
          batchSize: 1
          startingPosition: TRIM_HORIZON