service: api-productos

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x # o la versión de Node.js que prefieras
  timeout: 30  
  iam:
    role: arn:aws:iam::385255784123:role/LabRole
    # Añadir permisos para DynamoDB
    statements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:Query
          - dynamodb:Scan
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:*:table/prod_cursos_curses"
          - "arn:aws:dynamodb:${self:provider.region}:*:table/prod_user_curses"
  stage: dev
  region: us-east-1 #

functions:
  createCurso:
    handler: functions/createCurso.createCurso
    events:
      - http:
          path: /cursos
          method: post
          cors: true
          integration: lambda
          request:
            parameters:
              querystrings:
                tenant_id: true
                limit: false
                lastEvaluatedKey: false
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:385255784123:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token


  getCurso:
    handler: functions/getCurso.getCurso
    events:
      - http:
          path: /cursos/{id}
          method: get
          cors: true
          integration: lambda
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:385255784123:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  updateCurso:
    handler: functions/updateCurso.updateCurso
    events:
      - http:
          path: /cursos/{id}
          method: put
          cors: true
          integration: lambda
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:385255784123:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  deleteCurso:
    handler: functions/deleteCurso.deleteCurso
    events:
      - http:
          path: /cursos/{id}
          method: delete
          cors: true
          integration: lambda
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:385255784123:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
  listCursos:
    handler: functions/listCursos.listCursos
    events:
      - http:
          path: /cursos
          method: get
          cors: true
          integration: lambda
          authorizer:
            name: validarToken
            arn: arn:aws:lambda:${self:provider.region}:385255784123:function:api-usuarios-dev-validarToken
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
